# Generated by Django 4.2.7 on 2025-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('tipo_proyecto', models.CharField(max_length=50)),
                ('presupuesto', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.TextField(max_length=1000)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('archived', 'Archived')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
