# Generated by Django 4.2.7 on 2025-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL Slug')),
                ('image_url', models.URLField(help_text='URL of the book cover image', max_length=500, verbose_name='Image URL')),
                ('summary', models.TextField(help_text='Brief summary (max 300 characters)', max_length=300, verbose_name='Summary')),
                ('description', models.TextField(help_text='Detailed description of the book', verbose_name='Description')),
                ('keywords', models.CharField(help_text='Comma-separated keywords (e.g., fiction, mystery, thriller)', max_length=200, verbose_name='Keywords')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Personal rating from 1 to 5', max_digits=3, null=True, verbose_name='Rating (1-5)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('featured', models.BooleanField(default=False, help_text='Show as featured book', verbose_name='Featured')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
